export type LeadTemp = "NA" | "Warm" | "Hot";

export type LeadRow = {
  id: string;
  name: string;
  temp: LeadTemp;
  leadId: string;
  stage: string;
  source: string;
  subSource: string;
  project: string;
  lud: string;
  assigned: string;
  assignedInitials: string;
  assignedTitle?: string;
  /** Full name shown in lead detail drawer “Assigned to” */
  assignedDisplayName?: string;
  /** Funding in AI Demographic card when table `funding` is "-" */
  drawerFundingSource?: string;
  createDate: string;
  whatsapp: string;
  altNumber: string;
  email: string;
  preferredUnit: string;
  maxBudget: string;
  propertyStatus: string;
  purpose: string;
  otherPrefs: string;
  occupation: string;
  qualification: string;
  funding: string;
  budgetRange: string;
  preferredLocation: string;
  age: string;
  gender: string;
  company: string;
  state: string;
  city: string;
  region: string;
  designation: string;
};

export const STAGE_TAB_COUNTS = [
  { label: "All Leads", count: 5400, active: true },
  { label: "New Lead", count: 52 },
  { label: "Contacted", count: 26 },
  { label: "Prospects", count: 2 },
  { label: "Site Visit", count: 201 },
  { label: "Negotiation", count: 5 },
  { label: "Booked", count: 62 },
  { label: "Dropped", count: 1078 },
  { label: "Unqualified", count: 3749 },
  { label: "Is a CP", count: 228 },
] as const;

export const SAMPLE_LEADS: LeadRow[] = [
  {
    id: "1",
    name: "QA team test",
    temp: "NA",
    leadId: "L0326000181",
    stage: "Booked",
    source: "Digital Marketing",
    subSource: "Facebook",
    project: "Prasun Adara",
    lud: "10.04.2026",
    assigned: "ST",
    assignedInitials: "ST",
    assignedDisplayName: "sandeep Test",
    drawerFundingSource: "Self Funded",
    createDate: "2026-03-25T10:55:22.569Z",
    whatsapp: "XXXXXX4694",
    altNumber: "-",
    email: "-",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "1.50 - 1.60 cr",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "2",
    name: "Testttttt",
    temp: "NA",
    leadId: "L0326000182",
    stage: "Booked",
    source: "Digital Marketing",
    subSource: "LinkedIn",
    project: "Prasun Adara",
    lud: "10.04.2026",
    assigned: "ST",
    assignedInitials: "ST",
    createDate: "2026-03-25T11:08:25.727Z",
    whatsapp: "XXXXXX9994",
    altNumber: "-",
    email: "-",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "1.50 - 1.60 cr",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "3",
    name: "Budget Range",
    temp: "NA",
    leadId: "L0326000184",
    stage: "Booked",
    source: "Direct Site Visit",
    subSource: "99 Acres",
    project: "Prasun Adara",
    lud: "10.04.2026",
    assigned: "ST",
    assignedInitials: "ST",
    createDate: "2026-03-25T12:08:18.770Z",
    whatsapp: "XXXXXX5456",
    altNumber: "-",
    email: "-",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "2.0 cr +",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "4",
    name: "Kawal Lead Prasun",
    temp: "Warm",
    leadId: "L0226000001",
    stage: "Booked",
    source: "Others",
    subSource: "abc",
    project: "Prasun Adara",
    lud: "10.04.2026",
    assigned: "KN",
    assignedInitials: "KN",
    assignedTitle: "kawaljeet NonAdmin",
    createDate: "2026-02-12T13:46:37.441Z",
    whatsapp: "XXXXXX0494",
    altNumber: "-",
    email: "Kawaljeetgulati7@gmail.com",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "1.50 - 1.60 cr",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "5",
    name: "dsdfd dfdf",
    temp: "Hot",
    leadId: "L0226000084",
    stage: "Booked",
    source: "Channel Partner",
    subSource: "Kawaljeet gulati - dsfdsfds",
    project: "Prasun Adara",
    lud: "10.04.2026",
    assigned: "KN",
    assignedInitials: "KN",
    assignedTitle: "kawaljeet NonAdmin",
    createDate: "2026-02-25T05:07:50.466Z",
    whatsapp: "XXXXXX6875",
    altNumber: "-",
    email: "kishorkumar.beldar123@tcgre.com",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "1.50 - 1.60 cr",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "6",
    name: "test reception form",
    temp: "NA",
    leadId: "L0426000207",
    stage: "Booked",
    source: "Digital Marketing",
    subSource: "Google",
    project: "Prasun Adara",
    lud: "10.04.2026",
    assigned: "A",
    assignedInitials: "A",
    createDate: "2026-04-06T09:13:03.208Z",
    whatsapp: "XXXXXX9467",
    altNumber: "-",
    email: "-",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "-",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "7",
    name: "sandeep",
    temp: "Warm",
    leadId: "L0326000166",
    stage: "Site Visit",
    source: "Referral",
    subSource: "Test",
    project: "Prasun Adara",
    lud: "10.04.2026",
    assigned: "ST",
    assignedInitials: "ST",
    createDate: "2026-03-10T10:16:27.161Z",
    whatsapp: "XXXXXX5688",
    altNumber: "-",
    email: "-",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "1.50 - 1.60 cr",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "8",
    name: "Priyanka angre",
    temp: "NA",
    leadId: "PRA0326000008",
    stage: "Contacted",
    source: "Website",
    subSource: "Register Form",
    project: "Migration Project",
    lud: "10.04.2026",
    assigned: "SG",
    assignedInitials: "SG",
    createDate: "2026-03-02T07:11:01.000Z",
    whatsapp: "XXXXXX6859",
    altNumber: "-",
    email: "priya.angre@hotmail.com",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "1.50 - 1.60 cr",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "9",
    name: "No Name",
    temp: "NA",
    leadId: "PRA0426000029",
    stage: "New Lead",
    source: "Hoarding",
    subSource: "hd7 - Hadapsar",
    project: "Migration Project",
    lud: "10.04.2026",
    assigned: "SG",
    assignedInitials: "SG",
    createDate: "2026-04-09T09:34:38.000Z",
    whatsapp: "XXXXXX0088",
    altNumber: "-",
    email: "-",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "-",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
  {
    id: "10",
    name: "Test Lead",
    temp: "NA",
    leadId: "PRA0426000028",
    stage: "Unqualified",
    source: "Website",
    subSource: "-",
    project: "Migration Project",
    lud: "10.04.2026",
    assigned: "RP",
    assignedInitials: "RP",
    createDate: "2026-04-09T07:51:50.000Z",
    whatsapp: "XXXXXX2233",
    altNumber: "-",
    email: "test@test.com",
    preferredUnit: "-",
    maxBudget: "-",
    propertyStatus: "-",
    purpose: "-",
    otherPrefs: "-",
    occupation: "-",
    qualification: "-",
    funding: "-",
    budgetRange: "-",
    preferredLocation: "-",
    age: "-",
    gender: "-",
    company: "-",
    state: "-",
    city: "-",
    region: "-",
    designation: "-",
  },
];

export function stageBg(stage: string): string {
  const map: Record<string, string> = {
    Booked: "#c2fad5",
    "Site Visit": "#fdf0ab",
    Contacted: "#fcba74",
    "New Lead": "#c5ebff",
    Unqualified: "#ffa7cd",
    Negotiation: "#e0d4ff",
    Dropped: "#ffd4c4",
    Prospects: "#e8eaed",
    "Is a CP": "#d1c4e9",
  };
  return map[stage] ?? "#e9eaf1";
}
